export const dummydata = [
  {
    id: 1,
    index: "0",
    title: "Setting hotel rooming list",
    description: "create excel file",
    notification: false,
    time: "",
    priority: "middle",
    deadline: "",
    completed: false,
  },
  {
    id: 2,
    index: "1",
    title: "Marketing meeting",
    description: "weekly sales",
    notification: true,
    time: "22:06",
    priority: "top",
    deadline: "",
    completed: false,
  },
  {
    id: 3,
    index: "1",
    title: "Cooking for dinner",
    description: "",
    notification: true,
    time: "17:00",
    priority: "default",
    deadline: "",
    completed: true,
  },
  {
    id: 4,
    index: "5",
    title: "buy flower 🌷",
    description: "",
    notification: true,
    time: "10:00",
    priority: "default",
    deadline: "",
    completed: false,
  },
  {
    id: 5,
    index: "1",
    title: "Reading a book",
    description: "",
    notification: true,
    time: "14:00",
    priority: "top",
    deadline: "",
    completed: true,
  },
];
